//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Culqi_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta
    {
        public int ID_Cuenta { get; set; }
        public int ID_Banco { get; set; }
        public int ID_Usuario { get; set; }
        public int ID_Tipo_Cuenta { get; set; }
        public int ID_Moneda { get; set; }
        public int ID_Lugar { get; set; }
        public string Numero_Cuenta { get; set; }
    
        public virtual Banco Banco { get; set; }
        public virtual Lugar Lugar { get; set; }
        public virtual Tipo_Moneda Tipo_Moneda { get; set; }
        public virtual Tipo_Cuenta Tipo_Cuenta { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
