//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Culqi_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta
    {
        public int ID_Cuenta { get; set; }
        public int ID_Marca { get; set; }
        public string Tipo_Moneda { get; set; }
        public Nullable<int> ID_Usuario { get; set; }
        public string Numero_cuenta { get; set; }
    
        public virtual Marca Marca { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
