//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Culqi_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Deposito
    {
        public int ID_Deposito { get; set; }
        public Nullable<int> N_Operacion { get; set; }
        public Nullable<System.DateTime> Fecha_Desposito { get; set; }
        public string Concepto { get; set; }
        public Nullable<double> Monto { get; set; }
        public Nullable<double> Comision { get; set; }
        public Nullable<double> Monto_Depo { get; set; }
        public int ID_Detalle_Deposito { get; set; }
        public Nullable<System.DateTime> Fecha_Oper { get; set; }
    
        public virtual Deposito Deposito { get; set; }
    }
}
