//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Culqi_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Venta
    {
        public int ID_Venta { get; set; }
        public Nullable<System.DateTime> fecha_hora { get; set; }
        public string Descripcion { get; set; }
        public string correo_electronico { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Pais { get; set; }
        public string Ciudad { get; set; }
        public int ID_Detalle_Venta { get; set; }
        public string Dirección { get; set; }
    
        public virtual Venta Venta { get; set; }
    }
}
