//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Culqi_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medio_Pago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medio_Pago()
        {
            this.Venta = new HashSet<Venta>();
        }
    
        public int ID_Pago { get; set; }
        public Nullable<int> ID_Tarjeta { get; set; }
        public Nullable<int> ID_referencia { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Venta_Efectivo Venta_Efectivo { get; set; }
        public virtual Venta_Tarjeta Venta_Tarjeta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta> Venta { get; set; }
    }
}
