//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Culqi_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orden
    {
        public int ID_Orden { get; set; }
        public int ID_Link { get; set; }
        public Nullable<int> ID_Metodo_Pago { get; set; }
        public string Correo { get; set; }
    
        public virtual Link Link { get; set; }
        public virtual Metodo_Pago Metodo_Pago { get; set; }
    }
}
