//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Culqi_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rubro
    {
        public int ID_Rubro { get; set; }
        public int ID_Giro_Negocio { get; set; }
        public string Nombre_Rubro { get; set; }
    
        public virtual Categoria Categoria { get; set; }
    }
}
