//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Culqi_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int ID_Venta { get; set; }
        public Nullable<int> ID_Cip { get; set; }
        public Nullable<int> ID_Metodo_Tarjeta { get; set; }
        public int ID_Comercio { get; set; }
        public System.DateTime Fecha_Pago { get; set; }
    
        public virtual Cip_Efectivo Cip_Efectivo { get; set; }
        public virtual Comercio Comercio { get; set; }
        public virtual Metodo_Tarjeta Metodo_Tarjeta { get; set; }
    }
}
