//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Culqi_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta_Efectivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Venta_Efectivo()
        {
            this.Medio_Pago = new HashSet<Medio_Pago>();
        }
    
        public int ID_referencia { get; set; }
        public int ID_Estado_Efectivo { get; set; }
        public int Monto { get; set; }
        public string Correo { get; set; }
        public Nullable<System.DateTime> Fecha_Pago { get; set; }
    
        public virtual Estado_Efectivo Estado_Efectivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medio_Pago> Medio_Pago { get; set; }
    }
}
